# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Resistance is Futile
email: savior1980@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Resistance is futile es mi blog personal, donde doy rienda suelta a mi alocada Paranoia Personal™ y escribo sobre lo que me gusta. Pasen y Vean.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://resistancefutile.com" # the base hostname & protocol for your site
twitter_username: savior1980
github_username:  savior1980

# Build settings
markdown: kramdown

# Gems
gems:
 - jekyll-coffeescript
 - jekyll-textile-converter
 - jekyll-paginate
# Pages
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/feed.xml'

paginate: 5

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "savior1980"
      lsi: true
      excerpt_separator: <!--more-->
