---
layout: post
title: Mehagustado/Nomehagustado [28/06/2009]
date: '2009-06-28T00:00:00+00:00'
permalink: 2009/06/28/mehagustadonomehagustado-28062009/
---
- <strong>Nomehagustado</strong> que esta semana haya rendido tan poco en el curro. Ha sido un poco frustrante todo en general, desde la despreocupación del cliente rayando en lo preocupante (valga el oxímoron) a la poca entrega tanto por mi parte como del compi de proyecto y es que hay veces en las que hay que organizarse mejor y tirar palante de forma ordenada y no a trompicones y de cualquier manera.

- <strong>Mehagustado</strong> bastante que USA haya eliminado a España del mundial este peripatético de las confederaciones. Así seles ha acabado a algunos las ganas de encumbrar a un equipo antes de tiempo, señores que hemos ganado una Eurocopa y está muy bien, pero otra cosa es ya considerar este equipo <a href="http://www.telecinco.es/informativos/copaconfederaciones/indice/100004264/La+Leyenda+Roja">"La Leyenda Roja"</a> y <a href="http://www.elmundodeportivo.es/gen/20090617/53725562402/noticia/les-comparan-con-el-brasil-del-70.html">comprarlo con el Brasil del 70</a>, es que me parece de chiste. Espero que en el mundial hagamos un buen papel al menos hay equipo para ello pero sin tanto sobradismo por favor.

- <strong>Mehagustado</strong> mucho la berbena de Sant Joan que pasé en casa de unos colegas. Nos lo pasamos genial, bebimos bastante, charlamos con todo el mundo y vino una tipa que nos la vendieron como pornstar, se llamaba Francine, tenía rasgos asiáticos y vivía en San Francisco, pero creo que no, que no era <a href="http://www.francinedee.com/">Francine Dee</a>, en cambio fue muy agradable diciendo que le encanta Barcelona y que debemos ir a visitar San Francisco, según ella la ciudad <em>yankee</em> con más pasión por la cultura europea.

- <strong>Mehagustado</strong> bastante la aplicación <a href="http://macpaw.com/cleanmymac">CleanMyMac</a>, con la que he ganado 6GB de disco, eliminando sobretodo los binarios universales, las cachés y los idiomas que no uso. Una pena que la aplicación sea tan cara. En cambio <strong>nomehagustado</strong> nada gastarme 5.99 euros en la aplicación pro de 1password total para que el bookmarklet de momento no me funcione y no haya más novedades que hayan incluido, o sea que tengo la versión touch pero pagando un euro más, a ver si puedo enviarles un mail y quejarme.

- <strong>Mehagustado</strong> mucho que <a href="http://www.emilcar.es">emilcar</a>, en un acto de extraordinaria generosidad que le honra me haya cedido temporalmente una cuenta de pruebas de su licencia familiar de MobileMe, así he podido comprobar qué tal está el servicio, hacer alguna prueba con el FindMyiPhone y sobretodo comprobar como <strong>nomehagustado</strong> que el iPhone usando notificaciones push se zampe el 90% de batería en menos de un día. Por cierto <strong>mehaencantado</strong> y a todo friki que se precie también lo hará, <a href="http://www.emilcar.es/20090627/emilcarpodcast-promo-3/">la promo de su próximo podcast</a>, realmente brutal.

- <strong>Mehagustado</strong> ir a celebrar el Santo de mi hermano este sábado en casa de mis padres y menos mal que le compré una camiseta en lugar del eyeTV diversity! Probamos con el Hybrid y no engancha nada con la antenita (mi hermano no tiene toma de antena en la habitación, una genial idea que tuvo mi padre). 

- <strong>Mehagustado</strong> bastante ver <a href="http://www.bytheway.tv/?p=2341">el vídeo de Irene y Montsinya en Buenafuente</a>, son unas auténticas cracks.

- <strong>Mehagustado</strong> que me haya quedado decente la quiche que he hecho siguiendo <a href="http://www.directoalpaladar.com/recetas-de-legumbres-y-verduras/quiche-de-puerros-cebolla-y-bacon-receta">la receta de DalP</a>, a Cris lehagustado así que otro día me atreveré con alguna variación.

- <strong>Nomehagustado</strong> ver como el iPhone 3GS queda fuera de mi alcance, <a href="http://www.pixelydixel.com/2009/06/lo-que-cuesta-el-renove-del-iphone-3g-s-de-movistar.html">Píxel se encargó de revelarlo en una entrad de su blog</a>. La verdad el iPhone 3GS molaquetecagas, ladymandona tiene uno y es absolutamente genial, sin embargo no me parece un salto de calidad suficiente para los que teniendo el iPhone 3G, paguemos más de 500 euros por él. Me espero tranquilamente a que salga el año que viene un nuevo modelo, seguramente con rediseño exterior.

- <strong>Nomehagustado</strong> estar muy indeciso sobre la compra de un disco duro SSD. He visto varios vídeos en los que el tiempo de carga del sistema y el manejo de aplicaciones es realmente un chiste frente a un disco normal, pero es que me cuesta mucho pagar casi 300 euros por un disco de mucha menos capacidad que mi disco actual de 200GB. Megusta bastante el <a href="http://www.xataka.com/perifericos/corsair-ssd-p128-y-p64-de-alto-rendimiento-y-un-posible-precio-ajustado">P128 de Corsair que presentó Whiskito en xataka</a>, pero me duele pagar el gusto y las ganas por él. Además del follón que representa no tan solo la instalación del disco, si no el volver a instalar Leopard y toda la pesca, no quiero restaurar de TimeMachine, prefiero volver a partir de una instalación limpia.

- <strong>Mehagustado</strong> mucho volver a descargar toda la discografía de los <a href="http://www.eelstheband.com/">Eels</a>, ya que me había desaparecido el <em>Shootenanny!</em> y algun disco más. El nuevo disco, <em>Hombre Lobo</em> está muy bien también con canciones geniales como "Beginners Luck". Además compré el recopilatorio de caras b y rarezas <em>Useless Trinkets</em> en la iTunes Store con piezas de un valor inigualable como los remixes de Mr E's beatiful blues. Mark Oliver Everett es el amo, un puto genio, end of story.
