---
layout: post
title: 'Mission: Resurrect iBook G4 as a Media Center'
date: '2009-08-02T00:00:00+00:00'
permalink: http://resistancefutile.com/2009/08/02/mission-resurrect-ibook-g4-as-a-media-center/
---
<img src="http://resistancefutile.com/wp-content/zz1167ca28.jpg" alt="iBook + XBMC" title="iBook + XBMC" width="491" height="293" class="centro" />Hoy además de volver a la vida al *PowerMacG4* que teníamos olvidado (había que hacer un _Archive&Install_ de Tiger, actualizar el sistema y toda la pesca y nos daba palo, como buenos procrastinadores) me he propuesto actualizar el *iBookG4* y probar el "XBMC":http://xbmc.org/ que hace pocos meses sacaron una versión compatible con PPC. De esta forma pretendo que un Media Center decente (y no el sarnoso FrontRow) pueda leer del PowerMacG4 _over-the-wire_, es decir por Wifi (802.11g en este caso) y no tener que andar moviendo el MacBookPro cada dos por tres, puesto que si el invento funciona, ya dejo el iBook en el salón y listo. Falta por ver si el software tira como es debido y si con Wifi g, va tan fluido como con Wifi n.

El precio a pagar es el Apple Remote puesto que el iBook G4 no tiene mando ni receptor de infrarrojos, pero en eso intervienen ciertas aplicaciones para el iPhone con las que sí se puede actuar como un Apple Remote vía Wifi, en caso que todo aguante, ya me preocuparé por encontrar una app adecuada y que no sea cara para poder estar desde el sofá controlando el XBMC. La otra putada es el HD, la verdad es que contenido en HD prácticamente no vemos, pero está claro que la gráfica del iBook no da para un pimiento, pero bueno casi siempre vemos series y tal que nos bajamos en el PowerMac y que no es que tengan una calidad envidiable, o sea que en este punto mira, da igual, y si nunca tenemos algo en HD que queramos ver (cosa harto difícil porque Cristina no ve pelis, la vida es así amigos) pues entonces ya volvería a coger el MBP(MacBookPro).

Bueno luego actualizo la entrada y os cuento que tal ha ido la historia. Lo que hace uno por no mover el MBP(MacBookPro) unos metros las contadas ocasiones en las que vemos una serie en el comedor, en fin, ganas de sacar partido al iBookG4 que está acumulando polvo encima del PowerMacG4 y no uso para casi nada. 

*Actualización*: +FAIL+ descomunal, la maltrecha gráfica del iBookG4 me da para una pírrica resolución de 1366×768 cosa que no llega a cubrir toda la superficie de la tele y deja unos fabulosos contornos negros (grandes por cierto) en cada lado de la pantalla. Genial. Además la versión XBMC para PPC es una pseudo-versión Windows muy extraña en la que el BonJour brilla por su ausencia y los protocolos manzaneros también, básicamente hay que arremangarse y montarse un servidor de streming o algo por el estilo, de momento creo que no tocará más remedio que ir llevando el MBP unos metros a no ser que alguien se saque de la manga algún otro método mejor. 
