---
layout: post
title: There are two new boys in town
date: '2009-05-08T00:00:00+00:00'
permalink: http://resistancefutile.com/2009/05/08/there-are-two-new-boys-in-town/
---
<a href="http://www.flickr.com/photos/savior1980/3517402489/" title="Two new boys in town by salva7flickr, on Flickr"><img src="http://farm4.static.flickr.com/3364/3517402489_ee585589f7.jpg" width="500" height="375" alt="Two new boys in town" class="centro_borde" /></a>Al final decidí no comprar en <a href="http://ebay.es">ebay</a> el monitor ACD de 20" de segunda mano que me ofrecían gracias a los comentarios de muchos en twitter y al énfasis de miLady que me animaba a no comprarlo. Así que lo que hice fue reaprovechar el monitor <a href="http://images.google.es/images?hl=es&q=LG%20194WT&um=1&ie=UTF-8&sa=N&tab=wi">LG 194WT</a> que tenía conectado al PowerMacG4 y enchufarlo al MacBook Pro, también le arrebaté el teclado (uno de los blanquitos de metacrilato) y los enchufé al MacBook Pro. He de aclarar que la pantalla del MacBook Pro está en perfectas condiciones y que el teclado funciona perfectamente salvo que tengo la tecla A un poco suelta, simplemente quise otra configuración a raíz de ver que podía hacerme con un Apple Cinema Display. 

Ahora al PowerMacG4 accedo vía <strong>Compartir Pantalla</strong> (la aplicación está en Sistema-Librería-Core Services), que no es más que un VNC 'a-la-Mac' y funciona de maravilla. He ganado un espacio más que considerable en el escritorio y aunque de resolución me he quedado igual con <strong>1440x900</strong>, ahora veo mucho mejor todo. Lo que ocurrió es que el teclado blanquito a falta de usarlo y tal quedó un poco duro (o bueno no sé si siempre ha sido así, la verdad es que quién más ha usado ese teclado es Cris). Además que ocupaba mucho espacio en el escritorio, así que <strong>decidí comprar el teclado inalámbrico de Apple</strong>, el que va por Bluetooth, así no tendría cables, ganaría mucho más espacio y tendría un teclado en condiciones.  He de decir que estoy encantadísimo con él, funciona a la perfección (y eso que ya sabéis que he sido reacio a estos teclados) y configurarlo ha sido un juego de niños, <strong>vale cada uno de los 79 euros que pagué por él</strong> en el <a href="http://www.aprsam.cat/">APR de Mataró</a>.

La otra adquisición maquera viene por un regalazo que me hicieron ayer mis amigos del MundoReal&trade; me regalaron, un muñeco Bubble-Head de Darth Vader, una camiseta del Barça oficial y <strong>un iPod Shuffle de los nuevos</strong>, al que he llamado cariñosamente "Drone" para seguir con la racha de nombres de robot: Gort (iPod touch 1G), Locutus (iPhone 3G), Drone (iPod Shuffle 3G). Cosas que <strong>mehangustado</strong>: Su diseño ultra-minimalista, su conector USB, la caja y las instrucciones, la posibilidad de crear listas de reproducción y <em>smartlists</em> y bueno, el <em>voiceover</em> está currao, un poco raro porque es exactamente igual que el Voice Over de Mac pero está chulo. Por contra, lo que <strong>nomehagustado</strong> nada es que tengas que estar ligado a los auriculares de Apple, los otros no funcionan, ni con el SmartTalk de Griffin, lo cual es una putada, aunque seguramente es la excusa que necesitaba para comprar los auriculares in-ear de Apple. Además hay que destacar también negativamente que el crear listas y gestionar la música en iTunes es un poco <strong>arduo</strong>, ya que no sé si es por que tengo la 8.2 beta de iTunes o que pero a veces se queda como atrapado, tienes que esperar unos minutos a que vuelva en sí para seguir con lo que hacías y además no he podido actualizar a la 1.0.2 hasta que no he activado la gestión manual de música.

Pero bueno en general estoy contentísimo con mis nuevos chicos, <strong>mehangustado</strong> mucho los dos.
