---
layout: post
title: 'Mis primeros auriculares de diadema: AKG K 518 LE'
date: '2010-08-08T00:00:00+00:00'
permalink: http://resistancefutile.com/2010/08/08/mis-primeros-auriculares-de-diadema-akg-k-518-le/
---
<img src="http://resistancefutile.com/wp-content/image_red49350ef2da943.jpg" alt="" title="AKG K 518 LE" width="153" height="400" class="derecha_borde" />Me compré unos auriculares tipo diadema, para escuchar música en casa y en desplazamientos largos. La verdad que si pasas muchas horas en el avión o mucho tiempo en casa con los auriculares in-ear puestos, no es muy cómodo. Y evidentemente, nunca conseguirás un nivel de sonido tan perfecto como unos auriculares "de los de toda la vida de Dios", es decir unos tipo diadema. 

Así que ni corto ni perezoso al ver que "SopmacSL":http://sopmacsl.com se compraba unos "AKG K142 HD":http://www.akg.com/personal/K_142_HD,pcatid,8,pid,91,_psmand,1.html yo me compré unos "AKG K 518 LE":http://www.akg.com/personal/K_518_LE,pcatid,4,pid,705,_psmand,1.html, estuve probando varios modelos de auriculares, me encantaba la estética de los "dr. dre beat solo":http://beatsbydre.com/int/products/Products.aspx?pid=B5505 pero no su precio (180 euracos) y para los primeros auriculares que tengo, creo que es pasarse, así que pensé en gastarme menos de la mitad de esos en otros. Como sé que AKG es una marca contrastada y como digo tras probar algunos (en la fnac puedes probar un huevo de auriculares), de estos me moló bastante esos bajos potentes, y también la estética, me decidí a desembolsar los *69 euros* que valen.

<h3>Exterior</h3>
Son rollo DJ, se pliegan por tres ejes, eso hace que no ocupen mucho espacio y que uno se los pueda llevar de viaje, aunque evidentemente están pensados para cogerlos y poder escuchar rápidamente y de forma limpia lo que esté sonando en ese momento sin siquiera ponértelos, pimpam. Una vez puestos, se ajustan perfectamente a la cabeza, aislan bastante el sonido exterior y como tienen cobertura de piel son bastante cómodos de llevar. De su composición diré que el cable es un tanto corto, pero bueno, nada que no pueda arreglar un extensor. Los materiales de los que está compuesto son todos de calidad, plástico muy bien acabado, tacto fino y muy sólidos, bastante flexibles en su parte alta para ajustarse a todo tipo de cabezas, con los típicos extensores graduables en varias posiciones.

<h3>Sonido</h3>
Se nota muchísimo los bajos. Es muy potente y el rango dinámico que tienen es espectacular de 16Hz a 24KHz, más que de sobras para apreciar claramente (sin ser superman y tener un superoído, claro) todos los registros que suenan en una melodía. El sonido es claro, cristalino y brillante, con predominio de bajos pero sin ser exagerado. Por ejemplo, los Seinheiser pecan bastante de amplificar demasiado los bajos, estos en cambio son bastante equilibrados y aunque el empuje a la zona baja de frecuencias es potente, no llega a ser un incordio, todo lo contrario. Por ejemplo, ahora estoy escuchando "Mechanical Wonder" de OCS pues oigo clarísimamente el bajo dum-dum-dum cuando en otros auriculares, como los in-ear de Apple sí que se escucha pero no con un protagonismo tan bestia. 

El nivel de sonido que se consigue con ellos es brutal. Con el volumen alto escuchar tu canción favorita será como entrar en otra dimensión. Mientras escribo estas líneas suena "Life in technicolor II" de Coldplay y es como si tuviese a Chris Martin aquí mismo, dando un concierto a mi lado. Espectacular. Aunque sí es recomendable poner un volumen considerablemente bajo para poder escuchar música más tranquilamente en una sesión normal y larga, veréis que con muy poco volumen, estos auriculares truenan a base de bien. 

<h3>¿Dónde los encuentro?</h3>
Yo vivo cerca de BCN y los he encontrado en Fnac del triangle, en Plaça Cataluña. Por 69 euros. También estaban los AKG 518 DJ que son exactamente iguales a nivel de prestaciones y precio, pero varían un poco en estética son negros, en lugar de llevar unas franjas con color (yo he pillado los rojos) como el modelo LE, que es una edición limitada de ese modelo DJ. Creo que la relación calidad precio es acertada. Son unos buenos auriculares en conjunto, de momento estoy muy contento con ellos y representan una entrada muy buena al mundo de los auriculares tipo diadema.
