---
layout: post
title: ¿Por qué una Olympus EP-2?
date: '2011-10-23T00:00:00+00:00'
permalink: http://resistancefutile.com/2011/10/23/%c2%bfpor-que-una-olympus-ep-2/
---
<img src="http://resistancefutile.com/wp-content/AcW5oJ0CEAEixGj.jpg" alt="" title="Olympus EP-2" width="600" height="448" class="centro_borde" />Los que me conocen saben que llevaba un tiempo obsesionado con las cámaras híbridas, básicamente desde que salieron las "Nikon Serie 1":http://www.backfocus.es/blog/nikon-1-la-nueva-serie-de-camaras-de-objetivo-intercambiable-sin-espejo-de-nikon/. Quería una cámara secundaria de ese estilo. Hay muchas veces en las que llevarse la cámara réflex *no es cómodo*. Entre el cuerpo de la cámara, el objetivo polivalente, la blackrapid y algún filtro o incluso algún objetivo más (como el gran angular) por si la moscas... uno va cargado como un mulo, máxime cuando no va específicamente a hacer un _photowalk_ o a visitar algún sitio interesante fotográficamente hablando, así que para esas ocasiones en las que uno no quiere llevarse todo el equipo, una cámara secundaria y pequeña va genial.

Quería una cámara que tirara en *RAW*, eso lo tenía claro. También quería algo ligero y transportable y no un monstruo como las cámaras compactas de gama alta (me refiero a las Canon G11-12-13, las nikon P7000 o las Lumix de quinientos euros) y también tenía claro vista la experiencia anterior (tuvimos una Lumix TZ8) que no quería una _bridge_, para mí un tipo de cámaras que tiene lo malo de ambos mundos, sensores de compacta y tamaños de réflex. La Serie 1 de Nikon me encantó pero el precio me pareció desorbitado. Estaba claro que debía sacarme esa idea de la cabeza, no iba a pagar 800 euros por una cámara secundaria. 

Fue en ese momento cuando pensé que estaría bien apostar por una cámara del estilo de las Nikon Serie 1 y me lancé a ver qué opciones tenía, lo primero que miré son las *PEN de Olympus* y estéticamente me encantaron. Además el tamaño del sensor juega un papel importante en la calidad de los resultados y las Nikon tienen un sensor menor que el cuatro tercios que montan marcas como Olympus así que fui convenciéndome yo mismo, me dije, este tipo de cámaras va a ser muy interesante. En ese momento acababa de salir la EP-3 por 800 y pico euros y pensé que estaba otra vez en las mismas que con el caso de Nikon, es decir que iba a gastarme una pasta alucinante en algo que quiero pero como un actor secundario. Pero ese lanzamiento de la EP-3 había propiciado que el modelo anterior, la EP-2, bajara de precio. Miré en Pixmanía pero lo que realmente estaba bien de precio era la gama EPL y sobre todo, la EPL-1 (a unos 250 euros), y también fui a verla en la fnac pero sinceramente, así como las EP estéticamente son resultonas, las EPL echan para atrás, tienen pinta de compacta cutronga (cuando en realidad internamente son lo mismo que la EP). Fue en ese momento que marqué el límite, si en eBay encontraba una EP-1 o una EP-2 por el precio de la EPL-1 nueva, me tiraría de cabeza a por ella.

Y así ha sido, encontré un tipo canadiense que quería desprenderse de su EP-2 y gané la subasta por unos 250 euretes, exceptuando el envío desde Canadá, que me costó 30 euretes más, así que en total me habré gastado menos de trescientos euros envío incluido. Venía en perfecto estado de revista, ni una rallada, batería cargada, con sus embalajes originales, con todos los complementos de la caja original y con un filtro UV para el objetivo del Kit, un 14-42mm de Zuiko que también iba en la caja. 

Estoy todavía aprendiendo a caminar con esta nueva cámara. Casi ni me atrevo a hacer una primera _review_ pero sí me lanzo con una lista de cosas buenas y puntos a mejorar:

* *Mehangustado* mucho todas las opciones y los menús de la cámara van de lo fácil a lo avanzado, y es posible configurar una cantidad de opciones realmente enorme, diría que al mismo nivel que mi D5000. Además su acceso es rápido y directo, en este aspecto Olympus se lo ha currado.

* *Mehangustado* las posibilidades de configuración del enfoque (me encanta el modo automático+manual) y el LiveView, realmente bueno, nada que ver con el de mi D5000 que no sé ni para qué está, el de la EP-2 está actualizado con los parámetros de luz y muestra el 100% de lo que capturas, no se puede pedir más. Además los filtros artísticos mola mucho previsualizarlos, aunque eso sí, hacen que la cámara vaya a saltos... tiran abajo el rendimiento y hacen que sea difícil disparar ahí.

* *Noterminadegustarme* el formato cuatro tercios, aunque puedas seleccionar en la cámara el 3:2 clásico, el recorte no me gusta mucho. No sé supongo que es algo que tendré que acostumbrarme.

* *Nomegusta* que no tenga flash integrado, aunque el rango dinámico es buenísimo y a ISOs elevados se comporta con aplomo, creo que el flash es algo necesario. Además los accesorios son carísimos, el flash, el visor electrónico y el objetivo 17mm pancake pasan de los 200 euros, creo que antes de hacerme con ellos pasará mucho tiempo. Lo que sí he hecho es comprar un adaptador de Nikon G a M4/3 así podré montar los objetivos nikon en la PEN, aunque se conviertan en objetivos totalmente manuales. 

* *Megusta* mucho que el objetivo se esconda, la cámara más el objetivo del kit ocupan muy poco espacio y pueden llevarse a cualquier lado. La gente le tiene menos respeto que a una réflex, por el tema del LiveView principalmente y los modos automáticos son fáciles de seleccionar para que la gente no se líe, esto va bien especialmente cuando quieres que la gente te haga fotos con ella, una réflex siempre da mucho más miedo en las manos de otros. Pero sí es algo enrevesado el hecho que la lente se esconda, la gente no está acostumbrada a girarla y desbloquearla. Otro punto negativo es que el zoom va al revés que en el resto de objetivos que tengo de Nikon, hacia la derecha aumenta el zoom y a la izquierda disminuye y yo estoy completamente acostumbrado al revés.

* *Megusta* también que hay dos ruedas para cambiar exposición y apertura lo que ayuda mucho en los modos manuales. La batería es justita, pero aguanta unos 300 disparos, que no está nada mal, mi Nikon D5000 seguramente permite el doble pero desde luego en cuanto a batería, teniendo en cuenta que vas con la pantalla encendida siempre, es más que suficiente.

* *Nomegusta* y es algo que ya había leído en muchas reviews que el autofoco es lento, según comentan algunos esa lentitud va con el objetivo del kit y en otros objetivos la cosa va mejor, en realidad con condiciones de luz buenas, la cámara enfoca rápido así como el disparo que también es mucho más rápido que en otras bridge o compactas.

Creo que una vez haya hecho más fotos con la cámara tendré una opinión mejor sobre su calidad y sobre lo que me aporta, hoy por hoy, a poco más de 24h con ella tengo que decir que estoy más que satisfecho con la compra. Y eso de que con esta cámara voy a olvidar la Nikon, vamos yo estoy seguro de que no va a ser así.
