---
layout: post
title: De salsas picantes va la cosa
date: '2013-11-02T00:00:00+00:00'
permalink: 2013/09/08/de-salsas-picantes-va-la-cosa/
---
Hace mucho tiempo que el picante me mola. Es así, empezó gustándome el Tabasco con la carne, la salsa brava y de ahí ir subiendo. Me gusta la comida india y cuando voy siempre les digo que quiero lo que como con un punto picante, y en general se puede decir que casi siempre elijo el plato más picante de la carta de cualquier mejicano.

<img src="/assets/Captura-de-pantalla-2013-11-02-a-les-23.51.39.png" alt="Pain 100%" width="265" height="408" class="right" />En uno de mis viajes a London, en un Marks & Spencer compré "PAIN 100%":http://www.originaljuan.com/pain-100/pain-100-hot-sauce una salsa, bueno lo más picante que había probado nunca. Unas gotas y llorera. Y a partir de aquí fui investigando sobre salsas picantes y "la escala de picante de Scoville":http://en.wikipedia.org/wiki/Scoville_scale. He encontrado incluso un muy buen ranking sobre la escala Scoville, es el que publica "Scott Roberts en su blog":http://www.scottrobertsweb.com/scoville-scale/, todo un experto en la materia. Allí he visto que en realidad la salsa Pain 100% que encontré exageradamente picante, no es en realidad una salsa bien considerada dentro de la escala. A mí el Pain 100% me encantaba porque hacía que una comida sosa se volviese ultrapicante. Me lo mezclaba con el caldo de pollo para tener una sopa realmente picante, lo ponía en el guacamole para hacer una versión muy picante y refrescante al mismo tiempo.

Y casi no me queda Pain, así que en mi reciente viaje a NYC, tenía un to-do adicional en mi checklist, busqué un lugar donde tuviesen gran cantidad de salsas y especias, así que fui al "Kalustyans":http://kalustyans.com, un lugar de referencia. Como tuve poco tiempo, compré dos salsas casi por impulso, sabiendo que estaban arriba en la clasificación Scoville: "Da Bomb Ground Zero":http://www.originaljuan.com/da-bomb/da-bomb-ground-zero-hot-sauce  (casualmente del mismo fabricante que el Pain 100%) y "Blair's Ultra Death":http://extremefood.com/Ultra-Death-Sauce/ (una de las más picantes del mundo sin llegar al top 5 o las "gran reserva":http://extremefood.com/death-sauce-reserves/).

Bien, la primera que abrí fue la Da Bomb Ground Zero. Y el primer día aunque su sabor me encantó y es potentemente picante (mucho más que el Pain 100%), desgraciadamente no me sentó bien. Volví a probar y otra vez me sentó mal, así que la aparcaremos. Aclaro que solo consumí unas gotas y mezcladas con comida, bueno será que el concentrado de piña que lleva o el del lima no me sienta bien, no sé, la cosa es que con el Pain nunca tuve problemas de estómago y con el Da Bomb, dos de dos, así que mejor la dejamos en barbecho. En unos días abriré la Ultra Death a ver qué tal, tengo muchas ganas de ver qué tal es la salsa más picante de Blair y qué tal me sienta después del chasco del Da Bomb.
